from dataclasses import dataclass, field


PALETTE_COLOR_LIMIT = 16

PALETTE_FLEXOKI_DARK = "flexoki_dark"
PALETTE_FLEXOKI_LIGHT = "flexoki_light"
PALETTE_FLEXOKI_SYNTAX_DARK = "flexoki_syntax_dark"
PALETTE_FLEXOKI_SYNTAX_LIGHT = "flexoki_syntax_light"
DEFAULT_PALETTE = PALETTE_FLEXOKI_DARK
PALETTE_IDS = (
    PALETTE_FLEXOKI_DARK,
    PALETTE_FLEXOKI_SYNTAX_DARK,
    PALETTE_FLEXOKI_LIGHT,
    PALETTE_FLEXOKI_SYNTAX_LIGHT,
)
PALETTE_LABELS = {
    PALETTE_FLEXOKI_DARK: "Flexoki Dark",
    PALETTE_FLEXOKI_LIGHT: "Flexoki Light",
    PALETTE_FLEXOKI_SYNTAX_DARK: "Flexoki Syntax Dark",
    PALETTE_FLEXOKI_SYNTAX_LIGHT: "Flexoki Syntax Light",
}

ROLE_BG = "bg"
ROLE_BG_2 = "bg_2"
ROLE_MEMORY = "memory"
ROLE_UI = "ui"
ROLE_WALL = "wall"
ROLE_CORRIDOR = "corridor"
ROLE_FLOOR = "floor"
ROLE_INFO = "info"
ROLE_MAGIC = "magic"
ROLE_DOOR = "door"
ROLE_ACCENT = "accent"
ROLE_RARE = "rare"
ROLE_DANGER = "danger"
ROLE_HILITE = "hilite"
ROLE_TEXT = "text"
ROLE_SECTION = "section"
ROLE_TRAP = "trap"
ROLE_GOLD = "gold"
ROLE_PLAYER = "player"
ROLE_FLAG_ON = "flag_on"
ROLE_FLAG_OFF = "flag_off"
ROLE_STATUS_BAD = "status_bad"
ROLE_STATUS_WARN = "status_warn"
ROLE_STATUS_MIND = "status_mind"
ROLE_STATUS_BUFF = "status_buff"
ROLE_HP_LOW_FRAME_DIM = "hp_low_frame_dim"
ROLE_HP_LOW_FRAME_SHADOW = "hp_low_frame_shadow"
ROLE_HP_LOW_FRAME_MID = "hp_low_frame_mid"
ROLE_HP_LOW_FRAME_GLOW = "hp_low_frame_glow"

REQUIRED_PALETTE_ROLES = (
    ROLE_BG,
    ROLE_BG_2,
    ROLE_MEMORY,
    ROLE_UI,
    ROLE_WALL,
    ROLE_CORRIDOR,
    ROLE_FLOOR,
    ROLE_DOOR,
    ROLE_TRAP,
    ROLE_GOLD,
    ROLE_PLAYER,
    ROLE_FLAG_ON,
    ROLE_FLAG_OFF,
    ROLE_STATUS_BAD,
    ROLE_STATUS_WARN,
    ROLE_STATUS_MIND,
    ROLE_STATUS_BUFF,
    ROLE_TEXT,
    ROLE_HILITE,
    ROLE_SECTION,
    ROLE_HP_LOW_FRAME_DIM,
    ROLE_HP_LOW_FRAME_SHADOW,
    ROLE_HP_LOW_FRAME_MID,
    ROLE_HP_LOW_FRAME_GLOW,
)

MONSTER_BEAST = "beast"
MONSTER_UNDEAD = "undead"
MONSTER_MAGIC = "magic"
MONSTER_THIEF = "thief"
MONSTER_DEADLY = "deadly"
MONSTER_MIMIC = "mimic"
MONSTER_AQUATIC = "aquatic"
MONSTER_BASIC = "basic"
REQUIRED_MONSTER_ROLES = (
    MONSTER_BEAST,
    MONSTER_UNDEAD,
    MONSTER_MAGIC,
    MONSTER_THIEF,
    MONSTER_DEADLY,
    MONSTER_MIMIC,
    MONSTER_AQUATIC,
    MONSTER_BASIC,
)

BASE_ROLES = {
    ROLE_BG: 0,
    ROLE_BG_2: 1,
    ROLE_MEMORY: 3,
    ROLE_UI: 3,
    ROLE_WALL: 4,
    ROLE_CORRIDOR: 5,
    ROLE_FLOOR: 7,
    ROLE_INFO: 13,
    ROLE_MAGIC: 13,
    ROLE_DOOR: 8,
    ROLE_ACCENT: 12,
    ROLE_RARE: 13,
    ROLE_DANGER: 9,
    ROLE_HILITE: 11,
    ROLE_TEXT: 14,
    ROLE_SECTION: 15,
    ROLE_TRAP: 11,
    ROLE_GOLD: 11,
    ROLE_PLAYER: 14,
    ROLE_FLAG_ON: 11,
    ROLE_FLAG_OFF: 5,
    ROLE_STATUS_BAD: 9,
    ROLE_STATUS_WARN: 10,
    ROLE_STATUS_MIND: 13,
    ROLE_STATUS_BUFF: 12,
    ROLE_HP_LOW_FRAME_DIM: 1,
    ROLE_HP_LOW_FRAME_SHADOW: 3,
    ROLE_HP_LOW_FRAME_MID: 4,
    ROLE_HP_LOW_FRAME_GLOW: 5,
}

FLEXOKI_LIGHT_ROLES = dict(BASE_ROLES)
FLEXOKI_LIGHT_ROLES.update({
    ROLE_MEMORY: 5,
    ROLE_CORRIDOR: 4,
    ROLE_FLAG_OFF: 3,
    ROLE_STATUS_MIND: 2,
    ROLE_HP_LOW_FRAME_DIM: 1,
    ROLE_HP_LOW_FRAME_SHADOW: 3,
    ROLE_HP_LOW_FRAME_MID: 5,
    ROLE_HP_LOW_FRAME_GLOW: 4,
})

BASE_MONSTER_ROLES = {
    MONSTER_BEAST: 7,
    MONSTER_UNDEAD: 12,
    MONSTER_MAGIC: 13,
    MONSTER_THIEF: 10,
    MONSTER_DEADLY: 9,
    MONSTER_MIMIC: 13,
    MONSTER_AQUATIC: 12,
    MONSTER_BASIC: 14,
}

FLEXOKI_DARK_MONSTER_ROLES = dict(BASE_MONSTER_ROLES)
FLEXOKI_DARK_MONSTER_ROLES.update({
    MONSTER_MIMIC: 2,
})
FLEXOKI_DARK_MONSTER_OVERRIDES = {
    "P": 2,
    "U": 2,
}

FLEXOKI_LIGHT_MONSTER_ROLES = dict(FLEXOKI_DARK_MONSTER_ROLES)
FLEXOKI_LIGHT_MONSTER_ROLES.update({
    MONSTER_BEAST: 6,
})

SYNTAX_DARK_MONSTER_ROLES = dict(BASE_MONSTER_ROLES)
SYNTAX_DARK_MONSTER_ROLES.update({
    MONSTER_MIMIC: 10,
})
SYNTAX_DARK_MONSTER_OVERRIDES = {
    "P": 2,
    "U": 2,
}


@dataclass(frozen=True)
class PaletteTheme:
    id: str
    label: str
    colors: tuple[int, ...]
    roles: dict[str, int] = field(default_factory=dict)
    monster_roles: dict[str, int] = field(default_factory=dict)
    monster_overrides: dict[str, int] = field(default_factory=dict)


FLEXOKI_DARK_PALETTE = [
    0x100F0F, 0x1C1B1A, 0x4F3685, 0x343331,
    0x6F6E69, 0x878580, 0xDAD8CE, 0x66800B,
    0x71320D, 0xD14D41, 0xDA702C, 0xD0A215,
    0x3AA99F, 0x4385BE, 0xCECDC3, 0xFFFCF0,
]
FLEXOKI_LIGHT_PALETTE = [
    0xE6E4D9, 0xDAD8CE, 0x5E409D, 0xB7B5AC,
    0x878580, 0xB7B5AC, 0xA0AF54, 0x879A39,
    0xBC5215, 0xAF3029, 0xAD8301, 0xD0A215,
    0x24837B, 0x4385BE, 0x403E3C, 0x282726,
]
FLEXOKI_SYNTAX_DARK_PALETTE = [
    0x100F0F, 0x1C1B1A, 0x4F3685, 0x343331,
    0x6F6E69, 0x878580, 0xDAD8CE, 0x879A39,
    0xDA702C, 0xD14D41, 0xCE5D97, 0xD0A215,
    0x3AA99F, 0x4385BE, 0xCECDC3, 0xFFFCF0,
]
FLEXOKI_SYNTAX_LIGHT_PALETTE = [
    0xFFFCF0, 0xE6E4D9, 0x8B7EC8, 0xB7B5AC,
    0x6F6E69, 0x9F9D96, 0x879A39, 0x879A39,
    0xDA702C, 0xD14D41, 0xAD8301, 0xD0A215,
    0x3AA99F, 0x4385BE, 0x403E3C, 0x282726,
]

PALETTE_THEMES = {
    PALETTE_FLEXOKI_DARK: PaletteTheme(
        PALETTE_FLEXOKI_DARK,
        PALETTE_LABELS[PALETTE_FLEXOKI_DARK],
        FLEXOKI_DARK_PALETTE,
        dict(BASE_ROLES),
        dict(FLEXOKI_DARK_MONSTER_ROLES),
        dict(FLEXOKI_DARK_MONSTER_OVERRIDES),
    ),
    PALETTE_FLEXOKI_LIGHT: PaletteTheme(
        PALETTE_FLEXOKI_LIGHT,
        PALETTE_LABELS[PALETTE_FLEXOKI_LIGHT],
        FLEXOKI_LIGHT_PALETTE,
        dict(FLEXOKI_LIGHT_ROLES),
        dict(FLEXOKI_LIGHT_MONSTER_ROLES),
        {"K": 14},
    ),
    PALETTE_FLEXOKI_SYNTAX_DARK: PaletteTheme(
        PALETTE_FLEXOKI_SYNTAX_DARK,
        PALETTE_LABELS[PALETTE_FLEXOKI_SYNTAX_DARK],
        FLEXOKI_SYNTAX_DARK_PALETTE,
        dict(BASE_ROLES),
        dict(SYNTAX_DARK_MONSTER_ROLES),
        dict(SYNTAX_DARK_MONSTER_OVERRIDES),
    ),
    PALETTE_FLEXOKI_SYNTAX_LIGHT: PaletteTheme(
        PALETTE_FLEXOKI_SYNTAX_LIGHT,
        PALETTE_LABELS[PALETTE_FLEXOKI_SYNTAX_LIGHT],
        FLEXOKI_SYNTAX_LIGHT_PALETTE,
        dict(FLEXOKI_LIGHT_ROLES),
        dict(FLEXOKI_LIGHT_MONSTER_ROLES),
        {"K": 14},
    ),
}
PALETTES = {theme_id: theme.colors for theme_id, theme in PALETTE_THEMES.items()}

# Compatibility aliases for older saves/tests importing the former names.
PALETTE_GBC = PALETTE_FLEXOKI_DARK
PALETTE_GBC_HIGH_CONTRAST = PALETTE_FLEXOKI_SYNTAX_DARK
GBC_PALETTE = FLEXOKI_DARK_PALETTE
GBC_HIGH_CONTRAST_PALETTE = FLEXOKI_SYNTAX_DARK_PALETTE


def palette_theme(palette_id):
    return PALETTE_THEMES.get(palette_id, PALETTE_THEMES[DEFAULT_PALETTE])


def palette_role_color(palette_id, role):
    return palette_theme(palette_id).roles[role]
