from rogue_map import MAP_W, PLAY_H

FONT_ASCII_W, FONT_CJK_W, FONT_LINE_H = 6, 10, 12
SCR_W, SCR_H = 512, 320
TILE_W, TILE_H = 6, 12
ZV_COLS, ZV_ROWS = MAP_W, PLAY_H
ZV_PX_W = ZV_COLS * TILE_W
ZV_PX_H = ZV_ROWS * TILE_H
DEAD_ZONE_X = 8
DEAD_ZONE_Y = 5

ZV_X, ZV_Y = 16, 24
HUD_X = ZV_X
HUD_Y = 0
HUD_W = ZV_PX_W

MSG_LINES = 7
MSG_LINE_H = 10
MSG_X, MSG_Y = 4, SCR_H - MSG_LINES * MSG_LINE_H - 2
MSG_COLS = 23
MSG_TOAST_LINES = 7
MSG_TOAST_BRIGHT_TURNS = 0
MSG_TOAST_DIM_TURNS = 5
MSG_TOAST_FADE_COLORS = ((0, 9), (1, 5), (3, 6), (5, 3))
MSG_TOAST_SHADOW_COL = 0
MSG_TOAST_GRID_COL_EDGES = (0, 27, 54, MAP_W)
MSG_TOAST_GRID_ROW_EDGES = (0, 7, 14, PLAY_H)
