"""Online scoreboard UI text."""

from __future__ import annotations

from pyxel_rogue.rogue_lang import LANG_EN, LANG_JA

ONLINE_UI_TEXT = {
    LANG_EN: {
        "confirm_title": "Online Scoreboard",
        "confirm_prompt": "Set up online sync for scores?",
        "confirm_register": "A/Enter sync",
        "confirm_local": "B/Esc local only",
        "confirm_mark": "Guest scores stay local.",
        "language_hint": "Select/L Change Language（言語切替）",
        "score_title": "Scoreboard",
        "score_title_local": "My Rogue Chronicle",
        "score_title_weekly": "This Week's Challengers",
        "score_title_season": "Season Legends",
        "score_period_local": "Local",
        "score_tab_weekly": "This Week",
        "score_tab_season": "Season",
        "score_header": "   Score Name",
        "score_hint": "Left/Right: View  Select/Tab: Online Sync  B/Esc: Back",
        "score_register_prompt": "Online sync can post once per hour.",
        "score_register_hint": "A/Enter sync   B/Esc local only",
        "score_register_mark": "Guest scores stay local.",
        "score_guest_result": "Ranking refreshed. Guest mode.",
        "period_week": "This Week",
        "period_season": "Season",
        "local_only_hint": "Guest scores are not sent",
        "posted": "Posted",
        "post_after": "POST after",
        "register_title": "Online Sync",
        "register_prompt": "Enter an 8-char lowercase sync ID.",
        "register_cancel": "B/Esc cancels.",
        "register_local": "B/Esc keeps guest mode.",
        "register_hint": "A/Enter OK  B/Esc LOCAL ONLY",
        "register_cancel_hint": "A/Enter OK  B/Esc CANCEL",
        "local_confirm_title": "Local Only",
        "local_confirm_prompt": "Switch to guest mode?",
        "local_confirm_ok": "A/Enter switch",
        "local_confirm_cancel": "B/Esc cancel",
        "guest_confirm_title": "Guest Mode",
        "guest_confirm_prompt": "Switch to guest mode?",
        "guest_confirm_ok": "A/Enter switch",
        "guest_confirm_cancel": "B/Esc cancel",
        "language_title": "Language / 言語",
        "language_prompt": "Choose display language. / 表示言語を選んでください。",
        "language_select_hint": "A/Enter OK  D-pad/Arrows select",
        "pin_title": "6-Digit PIN",
        "pin_server": "This PIN is stored on the server",
        "pin_reuse": "without encryption. Do not reuse it.",
        "pin_link_title": "Verify PIN",
        "pin_link_server": "This name exists on the server.",
        "pin_link_reuse": "Enter its PIN to link this device.",
        "pin_hint": "A/Enter OK  B/Esc BACK",
        "sync_title": "Sync",
        "sync_scores": "Syncing scores...",
        "refresh_ranking": "Refreshing ranking...",
        "please_wait": "Please wait.",
        "checking user...": "checking user...",
        "registering user...": "setting up sync...",
        "linking user...": "linking user...",
        "posting local scores...": "posting local scores...",
        "loading scoreboard...": "loading scoreboard...",
        "searching scoreboard...": "searching scoreboard...",
        "Local only.": "Local only.",
        "Ranking refreshed. POST once per hour.": "Ranking refreshed. POST once per hour.",
        "Ranking refreshed. No local scores yet.": "Ranking refreshed. No local scores yet.",
        "Score posted. Ranking refreshed.": "Score posted. Ranking refreshed.",
        "Refresh failed. POST once per hour.": "Refresh failed. POST once per hour.",
        "Refresh failed. No local scores yet.": "Refresh failed. No local scores yet.",
        "Authentication failed. Register again.": "Authentication failed. Check sync ID.",
        "Score posted. Ranking refresh failed.": "Score posted. Ranking refresh failed.",
        "That user name is already registered.": "That user name is already registered.",
        "Could not check user. Try again.": "Could not check user. Try again.",
        "Name exists. Enter its 6-digit PIN.": "Name exists. Enter its 6-digit PIN.",
        "That name belongs to another player.": "That name belongs to another player.",
        "Registration failed.": "Sync setup failed.",
        "Enter a name.": "Enter a name.",
        "Ranking refreshed. Guest mode.": "Ranking refreshed. Guest mode.",
    },
    LANG_JA: {
        "confirm_title": "オンラインスコア",
        "confirm_prompt": "オンラインスコアを同期しますか?",
        "confirm_register": "A/Enter 同期",
        "confirm_local": "B/Esc ローカルのみ",
        "confirm_mark": "ゲストのスコアはローカルのみです。",
        "language_hint": "Select/L 言語切替",
        "score_title": "スコアボード",
        "score_title_local": "冒険の記録",
        "score_title_weekly": "今週の挑戦者",
        "score_title_season": "今季のレジェンド",
        "score_period_local": "ローカル",
        "score_tab_weekly": "今週",
        "score_tab_season": "今季",
        "score_header": "   得点 名前",
        "score_hint": "左右: 表示切替  Select/Tab: オンライン同期  B/Esc: 戻る",
        "score_register_prompt": "オンライン同期で1時間に1回投稿できます。",
        "score_register_hint": "A/Enter 同期  B/Esc ローカルのみ",
        "score_register_mark": "ゲストのスコアはローカルのみです。",
        "score_guest_result": "ランキング更新。ゲストモード。",
        "period_week": "今週",
        "period_season": "今季",
        "local_only_hint": "ゲストのスコアは送信されません",
        "posted": "投稿",
        "post_after": "POST可能",
        "register_title": "オンライン同期",
        "register_prompt": "8文字の小文字IDで同期します。",
        "register_cancel": "B/Esc キャンセル",
        "register_local": "B/Escでゲストモードのまま。",
        "register_hint": "A/Enter 決定  B/Esc ローカルのみ",
        "register_cancel_hint": "A/Enter 決定  B/Esc キャンセル",
        "local_confirm_title": "ローカル専用",
        "local_confirm_prompt": "ゲストモードに切り替えますか?",
        "local_confirm_ok": "A/Enter 切替",
        "local_confirm_cancel": "B/Esc キャンセル",
        "guest_confirm_title": "ゲストモード",
        "guest_confirm_prompt": "ゲストモードに切り替えますか?",
        "guest_confirm_ok": "A/Enter 切替",
        "guest_confirm_cancel": "B/Esc キャンセル",
        "language_title": "言語",
        "language_prompt": "表示言語を選んでください。",
        "language_select_hint": "A/Enter 決定  方向キー 選択",
        "pin_title": "6桁PIN",
        "pin_server": "PINはサーバに平文保存されます。",
        "pin_reuse": "他の場所のパスワードを使わないでください。",
        "pin_link_title": "PIN確認",
        "pin_link_server": "この名前はサーバにあります。",
        "pin_link_reuse": "本人ならPINを入力してください。",
        "pin_hint": "A/Enter 決定  B/Esc 戻る",
        "sync_title": "通信",
        "sync_scores": "スコア同期中...",
        "refresh_ranking": "ランキング更新中...",
        "please_wait": "お待ちください。",
        "checking user...": "ユーザを確認中...",
        "registering user...": "同期ID確認中...",
        "linking user...": "リンク通信中...",
        "posting local scores...": "ローカルスコア送信中...",
        "loading scoreboard...": "スコアボード読込中...",
        "searching scoreboard...": "スコアボード検索中...",
        "Local only.": "ローカルのみ。",
        "Ranking refreshed. POST once per hour.": "ランキング更新。POSTは1時間に1回。",
        "Ranking refreshed. No local scores yet.": "ランキング更新。ローカルスコアなし。",
        "Score posted. Ranking refreshed.": "スコア投稿。ランキング更新。",
        "Refresh failed. POST once per hour.": "更新失敗。POSTは1時間に1回。",
        "Refresh failed. No local scores yet.": "更新失敗。ローカルスコアなし。",
        "Authentication failed. Register again.": "認証失敗。同期IDを確認してください。",
        "Score posted. Ranking refresh failed.": "スコア投稿。ランキング更新失敗。",
        "That user name is already registered.": "その名前は登録済みです。",
        "Could not check user. Try again.": "ユーザ確認に失敗しました。",
        "Name exists. Enter its 6-digit PIN.": "登録済み名です。6桁PINを入力。",
        "That name belongs to another player.": "その名前は別プレイヤーのものです。",
        "Registration failed.": "同期設定失敗。",
        "Enter a name.": "名前を入力してください。",
        "Ranking refreshed. Guest mode.": "ランキング更新。ゲストモード。",
    },
}


def online_text(lang, key):
    lang = lang if lang in (LANG_EN, LANG_JA) else LANG_EN
    table = ONLINE_UI_TEXT.get(lang, ONLINE_UI_TEXT[LANG_EN])
    return table.get(key, ONLINE_UI_TEXT[LANG_EN].get(key, key))
