# Generated from assets/messages/*.json for Pyxel Web launcher fallback.
EN_MESSAGES = {
  "armor.not_wearing_armor": "not wearing armor",
  "armor.was": "was",
  "armor.wearing_item": "wearing {item}",
  "armor.wearing_item_item2": " wearing {item}) {item2}",
  "armor.you_are_already_wearing_some": "you are already wearing some",
  "armor.you_are_now": "you are now ",
  "armor.you_arent_wearing_any_armor": "you aren't wearing any armor",
  "armor.you_cant_wear_that": "you can't wear that",
  "armor.you_ll_have_to_take_it_off_first": ".  you'll have to take it off first",
  "armor.you_used_to_be": "you used to be",
  "chase.couldnt_find_monster_in_runto_at_x_y": "couldn't find monster in runto at ({x},{y})",
  "chase.in_some_bizarre_place_x_y": "in some bizarre place ({x}, {y})",
  "command.a_secret_door": "a secret door",
  "command.blank": "",
  "command.call_it": "call it: ",
  "command.called_value": "called \"{value}\"",
  "command.character_you_want_help_for_for_all": "character you want help for (* for all): ",
  "command.food_left_count": "food left: {count}",
  "command.i_see": "I see ",
  "command.i_see_no_way_down": "I see no way down",
  "command.i_see_no_way_up": "I see no way up",
  "command.illegal_command_command": "illegal command '{command}'",
  "command.inpack_count": "inpack = {count}",
  "command.item_value": "{item}) {value}",
  "command.no_monster_there": "no monster there",
  "command.no_trap_there": "no trap there",
  "command.not_wizard_any_more": "not wizard any more",
  "command.nothing_here": "nothing here",
  "command.sorry": "sorry",
  "command.that_has_already_been_identified": "that has already been identified",
  "command.there_is": "there is ",
  "command.to_pick_up": " to pick up",
  "command.unknown_character_command": "unknown character '{command}'",
  "command.value": " {value}",
  "command.value_nothing": "{value} nothing",
  "command.value_value2": "{value}{value2}",
  "command.value_value2_2": "'{value}': {value2}",
  "command.version_version_mctesq_was_here": "version {version}. (mctesq was here)",
  "command.was": "Was ",
  "command.what_do_you_want_identified": "what do you want identified? ",
  "command.what_do_you_want_to_call_it": "what do you want to call it? ",
  "command.x_y": "@ {x},{y}",
  "command.you_are": "you are ",
  "command.you_are_suddenly_as_smart_as_ken_arnold_in_dungeon_level": "you are suddenly as smart as Ken Arnold in dungeon #{level}",
  "command.you_are_value": "you are {value} (",
  "command.you_can_move_again": "you can move again",
  "command.you_cant_call_that_anything": "you can't call that anything",
  "command.you_cant_you_re_floating_off_the_ground": "you can't.  you're floating off the ground!",
  "command.you_feel_a_wrenching_sensation_in_your_gut": "you feel a wrenching sensation in your gut",
  "command.you_found": "you found ",
  "command.you_have_found": "you have found ",
  "command.you_havent_typed_a_command_yet": "you haven't typed a command yet",
  "command.your_way_is_magically_blocked": "your way is magically blocked",
  "daemons.bummer_you_ve_hit_the_ground": "bummer!  you've hit the ground",
  "daemons.everything_looks_so_boring_now": "Everything looks SO boring now",
  "daemons.far_out_everything_is_all_cosmic_again": "far out!  Everything is all cosmic again",
  "daemons.getting_hungry": "getting hungry",
  "daemons.getting_the_munchies": "getting the munchies",
  "daemons.the_munchies_are_interfering_with_your_motor_capabilites": "the munchies are interfering with your motor capabilites",
  "daemons.the_munchies_overpower_your_motor_capabilities": "the munchies overpower your motor capabilities.  ",
  "daemons.the_veil_of_darkness_lifts": "the veil of darkness lifts",
  "daemons.you_are_getting_the_munchies": "you are getting the munchies",
  "daemons.you_are_starting_to_feel_weak": "you are starting to feel weak",
  "daemons.you_are_starting_to_get_hungry": "you are starting to get hungry",
  "daemons.you_faint": "you faint",
  "daemons.you_feel_less_value_now": "you feel less {value} now",
  "daemons.you_feel_too_weak_from_lack_of_food": "you feel too weak from lack of food.  ",
  "daemons.you_feel_yourself_slowing_down": "you feel yourself slowing down",
  "daemons.you_float_gently_to_the_ground": "you float gently to the ground",
  "daemons.you_freak_out": "you freak out",
  "extern.a_beartrap": "a beartrap",
  "extern.a_mysterious_trap": "a mysterious trap",
  "extern.a_poison_dart_trap": "a poison dart trap",
  "extern.a_rust_trap": "a rust trap",
  "extern.a_sleeping_gas_trap": "a sleeping gas trap",
  "extern.a_teleport_trap": "a teleport trap",
  "extern.a_trapdoor": "a trapdoor",
  "extern.an_arrow_trap": "an arrow trap",
  "fight.a_bite_has_weakened_you": "a bite has weakened you",
  "fight.a_bite_momentarily_weakens_you": "a bite momentarily weakens you",
  "fight.barely_miss": " barely miss",
  "fight.barely_misses": " barely misses",
  "fight.bite_has_no_effect": "bite has no effect",
  "fight.blank": ".  ",
  "fight.by_the_subject": " by the {subject}",
  "fight.defeated": ".  Defeated ",
  "fight.defeated_2": "defeated ",
  "fight.defeated_target": "Defeated {target}",
  "fight.doesnt_hit": " doesn't hit",
  "fight.dont_hit": " don't hit",
  "fight.has_injured": " has injured ",
  "fight.have_injured": " have injured ",
  "fight.heavy_that_s_a_nasty_critter": "heavy!  That's a nasty critter!",
  "fight.hit": " hit ",
  "fight.miss": " miss",
  "fight.misses": " misses",
  "fight.monster_hit": "{subject} hit you",
  "fight.monster_hit_excellent": "{subject} scored an excellent hit on you",
  "fight.monster_hit_injured": "{subject} has injured you",
  "fight.monster_hit_swing": "{subject} swings and hits you",
  "fight.monster_miss": "{subject} misses you",
  "fight.monster_miss_barely": "{subject} barely misses you",
  "fight.monster_miss_doesnt_hit": "{subject} doesn't hit you",
  "fight.monster_miss_swing": "{subject} swings and misses you",
  "fight.player_hit": "you hit {target}",
  "fight.player_hit_excellent": "you scored an excellent hit on {target}",
  "fight.player_hit_injured": "you have injured {target}",
  "fight.player_hit_swing": "you swing and hit {target}",
  "fight.player_miss": "you miss {target}",
  "fight.player_miss_barely": "you barely miss {target}",
  "fight.player_miss_dont_hit": "you don't hit {target}",
  "fight.player_miss_swing": "you swing and miss {target}",
  "fight.scored_an_excellent_hit_on": " scored an excellent hit on ",
  "fight.she_stole_target": "she stole {target}!",
  "fight.subject": "{subject}",
  "fight.subject_2": " {subject}",
  "fight.subject_appears_confused": "{subject} appears confused",
  "fight.swing_and_hit": " swing and hit ",
  "fight.swing_and_miss": " swing and miss",
  "fight.swings_and_hits": " swings and hits ",
  "fight.swings_and_misses": " swings and misses",
  "fight.the_subject_hits": "the {subject} hits ",
  "fight.the_subject_misses": "the {subject} misses ",
  "fight.thrown_weapon_hits": "the {item} hits {target}",
  "fight.thrown_weapon_misses": "the {item} misses {target}",
  "fight.wait_that_s_a_xeroc": "wait!  That's a xeroc!",
  "fight.you_are_frozen": "you are frozen by {subject}",
  "fight.you_feel_a_bite_in_your_leg_and_now_feel_weaker": "you feel a bite in your leg and now feel weaker",
  "fight.you_have": "you have ",
  "fight.you_have_defeated_target": "you have defeated {target}",
  "fight.you_hit": "you hit ",
  "fight.you_hit_target": "you hit {target}",
  "fight.you_missed": "you missed ",
  "fight.you_missed_target": "you missed {target}",
  "fight.you_suddenly_feel_weaker": "you suddenly feel weaker",
  "fight.your_hands_stop_glowing_color": "your hands stop glowing {color}",
  "fight.your_purse_feels_lighter": "your purse feels lighter",
  "io.blank": "",
  "io.faint": "Faint",
  "io.hungry": "Hungry",
  "io.level_level_gold_gold_hp_hp_width_hp_str_max_hp_width_max_hp_arm_strengt": "Level: {level}  Gold: {gold}  Hp: {hp_width}({hp})  Str: {max_hp_width}({max_hp})  Arm: {strength}  Exp: {max_strength}/{armor}  {exp_level}",
  "io.weak": "Weak",
  "info.guide_default": "Left/Right: Tabs   Select/B: Close",
  "info.guide_log": "Up/Down: Scroll   Left/Right: Tabs   Select/B: Close",
  "info.help": "Help",
  "info.inventory": "Inventory",
  "info.log": "Log",
  "info.settings": "Settings",
  "info.title": "Info",
  "item.being_worn": "(being worn)",
  "item.on_left_hand": "(on left hand)",
  "item.on_right_hand": "(on right hand)",
  "item.protection": "protection {value}",
  "item.weapon_in_hand": "(weapon in hand)",
  "list.ran_out_of_memory_after_count_items": "ran out of memory after {count} items",
  "main.really_quit": "really quit?",
  "menu.action": "Action",
  "menu.assist": "Assist",
  "menu.call": "Call",
  "menu.discoveries": "Disc",
  "menu.drop": "Drop",
  "menu.eat": "Eat",
  "menu.help": "Help",
  "menu.identify": "Identify",
  "menu.inventory": "Inventory",
  "menu.language": "Language",
  "menu.palette": "Palette",
  "menu.pickup": "Pickup",
  "menu.picky_inventory": "Inventory",
  "menu.quit": "Quit",
  "menu.put_on": "Put on",
  "menu.quaff": "Quaff",
  "menu.read": "Read",
  "menu.remove_ring": "Remove",
  "menu.search": "Search",
  "menu.take_off": "Take off",
  "menu.take_off_armor": "Take off",
  "menu.throw": "Throw",
  "menu.trap": "Trap",
  "menu.wear": "Wear",
  "menu.wield": "Wield",
  "menu.zap": "Zap",
  "misc.call_it": "call it: ",
  "misc.in_use": "in use",
  "misc.my_that_was_a_yummy_value": "my, that was a yummy {value}",
  "misc.that_s_already": "That's already ",
  "misc.that_s_inedible": "that's Inedible!",
  "misc.ugh_you_would_get_ill_if_you_ate_that": "ugh, you would get ill if you ate that",
  "misc.value_that_tasted_good": "{value}, that tasted good",
  "misc.value_this_food_tastes_awful": "{value}, this food tastes awful",
  "misc.welcome_to_level_level": "welcome to level {level}",
  "misc.what_do_you_want_to_call_it": "what do you want to call it? ",
  "misc.which_direction": "which direction? ",
  "misc.yuk": "yuk",
  "misc.yum": "yum",
  "misc.you_faint_from_exhaustion": "you faint from exhaustion",
  "monsters.blank": "'",
  "monsters.cant_find_monster_in_wake_monster": "can't find monster in wake_monster",
  "monsters.s_gaze_has_confused_you": "s gaze has confused you",
  "monsters.started_a_wandering_subject": "started a wandering {subject}",
  "monsters.subject": "{subject}",
  "move.a_color_light_flashes_in_your_eyes": "a {color} light flashes in your eyes",
  "move.a_gush_of_water_hits_you_on_the_head": "a gush of water hits you on the head",
  "move.a_poisoned_dart_killed_you": "a poisoned dart killed you",
  "move.a_small_dart_just_hit_you_in_the_shoulder": "a small dart just hit you in the shoulder",
  "move.a_small_dart_whizzes_by_your_ear_and_vanishes": "a small dart whizzes by your ear and vanishes",
  "move.a_spike_shoots_past_your_ear": "a spike shoots past your ear!",
  "move.a_strange_white_mist_envelops_you_and_you_fall_asleep": "a strange white mist envelops you and you fall asleep",
  "move.an_arrow_killed_you": "an arrow killed you",
  "move.an_arrow_shoots_past_you": "an arrow shoots past you",
  "move.multi_colored_lines_swirl_around_you_then_fade": "multi-colored lines swirl around you, then fade",
  "move.oh_no_an_arrow_shot_you": "oh no! An arrow shot you",
  "move.the_light_in_here_suddenly_seems_color": "the light in here suddenly seems {color}",
  "move.the_rust_vanishes_instantly": "the rust vanishes instantly",
  "move.time_now_seems_to_be_going_slower": "time now seems to be going slower",
  "move.value_sparks_dance_across_your_armor": "{value} sparks dance across your armor",
  "move.you_are_being_held": "you are being held",
  "move.you_are_caught_in_a_bear_trap": "you are caught in a bear trap",
  "move.you_are_still_stuck_in_the_bear_trap": "you are still stuck in the bear trap",
  "move.you_are_suddenly_in_a_parallel_dimension": "you are suddenly in a parallel dimension",
  "move.you_feel_a_sting_in_the_side_of_your_neck": "you feel a sting in the side of your neck",
  "move.you_feel_time_speed_up_suddenly": "you feel time speed up suddenly",
  "move.you_fell_into_a_trap": "you fell into a trap!",
  "move.you_pack_turns_value": "you pack turns {value}!",
  "move.you_suddenly_feel_very_thirsty": "you suddenly feel very thirsty",
  "move.your_armor_appears_to_be_weaker_now_oh_my": "your armor appears to be weaker now. Oh my!",
  "move.your_armor_weakens": "your armor weakens",
  "pack.a_item": "a) {item}",
  "pack.blank": "",
  "pack.count_gold_pieces": "{count} gold pieces",
  "pack.empty_handed": "empty handed",
  "pack.for_list": "? (* for list): ",
  "pack.in_your_pack": " in your pack",
  "pack.item": "item: ",
  "pack.item_is_not_a_valid_item": "'{item}' is not a valid item",
  "pack.item_item2": "{item} ({item2})",
  "pack.item_item2_2": "{item}) {item2}",
  "pack.item_not_in_pack": "'{item}' not in pack",
  "pack.moved_onto_item": "moved onto {item}",
  "pack.no_room": "no room",
  "pack.nothing_appropriate": "nothing appropriate",
  "pack.the_scroll_turns_to_dust_as_you_pick_it_up": "the scroll turns to dust as you pick it up",
  "pack.there_s": "there's ",
  "pack.what": " what",
  "pack.which_item_do_you_wish_to_inventory": "which item do you wish to inventory: ",
  "pack.which_object_do_you_want_to": "which object do you want to ",
  "pack.you": "you ",
  "pack.you_are_empty_handed": "you are empty handed",
  "pack.you_arent_carrying_anything": "you aren't carrying anything",
  "pack.you_dont_have_anything_appropriate": "you don't have anything appropriate",
  "pack.you_found": "you found ",
  "pack.you_now_have": "you now have ",
  "pack.you_ran_out": "you ran out",
  "passages.warning_connectivity_problem_on_this_level": "warning, connectivity problem on this level",
  "potions.a_cloak_of_darkness_falls_around_you": "a cloak of darkness falls around you",
  "potions.hey_this_tastes_great_it_make_you_feel_warm_all_over": "hey, this tastes great.  It make you feel warm all over",
  "potions.oh_bummer_everything_is_dark_help": "oh, bummer!  Everything is dark!  Help!",
  "potions.oh_wow_everything_seems_so_cosmic": "Oh, wow!  Everything seems so cosmic!",
  "potions.oh_wow_you_re_floating_in_the_air": "oh, wow!  you're floating in the air!",
  "potions.that_s_undrinkable": "that's undrinkable",
  "potions.wait_what_s_going_on_here_huh_what_who": "wait, what's going on here. Huh? What? Who?",
  "potions.what_a_tripy_feeling": "what a tripy feeling!",
  "potions.what_an_odd_tasting_potion": "what an odd tasting potion!",
  "potions.you_begin_to_feel_better": "you begin to feel better",
  "potions.you_begin_to_feel_much_better": "you begin to feel much better",
  "potions.you_feel_momentarily_sick": "you feel momentarily sick",
  "potions.you_feel_stronger_now_what_bulging_muscles": "you feel stronger, now.  What bulging muscles!",
  "potions.you_feel_very_sick_now": "you feel very sick now",
  "potions.you_feel_yourself_moving_much_faster": "you feel yourself moving much faster",
  "potions.you_have_a_item_feeling_for_a_moment_then_it_passes": "you have a {item} feeling for a moment, then it passes",
  "potions.you_start_to_float_in_the_air": "you start to float in the air",
  "potions.you_suddenly_feel_much_more_skillful": "you suddenly feel much more skillful",
  "potions.this_potion_tastes_like_item_juice": "this potion tastes like {item} juice",
  "potions.yuk_why_would_you_want_to_drink_that": "yuk! Why would you want to drink that?",
  "pyxel.already_ring_each_hand": "you already have a ring on each hand",
  "pyxel.are_weak": "you are weak",
  "pyxel.armor_glows": "your armor glows!",
  "pyxel.can_see_invisible_monsters": "you can see invisible monsters",
  "pyxel.cant_appears_cursed": "you can't. It appears to be cursed",
  "pyxel.cant_let_go": "you can't let go!",
  "pyxel.cant_let_go_short": "Can't let go!",
  "pyxel.color_sparks_dance_armor": "{color} sparks dance across your armor",
  "pyxel.cursed_armor_wont_come_off": "Cursed armor won't come off!",
  "pyxel.darkness_falls": "Darkness falls",
  "pyxel.defeated_monster_exp": "you defeated the {monster}. ({exp} exp)",
  "pyxel.descend_to_depth": "you descend to depth {depth}...",
  "pyxel.diagonal_assist_off": "Diagonal assist OFF",
  "pyxel.diagonal_assist_on": "Diagonal assist ON",
  "pyxel.died_restart": "you died... [A/Start] to restart",
  "pyxel.drop_item": "you drop the {item}",
  "pyxel.dungeon_depth": "Dungeon depth {depth}",
  "pyxel.eat_item_yum": "you eat the {item}. Yum!",
  "pyxel.equipment_feels_lighter": "your equipment feels lighter",
  "pyxel.escaped_with_amulet": "you escaped with the Amulet of Yendor!",
  "pyxel.escaped_with_nyandor": "you return the guild's cat. the guild is satisfied.",
  "pyxel.faint_from_lack_of_food": "you faint from lack of food",
  "pyxel.fall_asleep": "you fall asleep",
  "pyxel.feel_better_amount": "you feel better. (+{count})",
  "pyxel.feel_confused": "you feel confused",
  "pyxel.feel_confused_bang": "you feel confused!",
  "pyxel.feel_hungry": "you feel hungry",
  "pyxel.feel_much_better_amount": "you feel much better. (+{count})",
  "pyxel.feel_sense_of_loss": "you feel a sense of loss",
  "pyxel.feel_sick_strength_loss": "you feel sick. (Str -{count})",
  "pyxel.feel_vaguely_uneasy": "you feel vaguely uneasy",
  "pixel.nyandor_cat_recovered": "you recover the cat. it objects.",
  "pixel.nyandor_vitory_line1": "You recovered the guild's cat",
  "pixel.nyandor_vitory_line2": "and returned safely.",
  "pyxel.nyandor_cat_drop_blocked": "the cat is not to be dropped.",
  "pyxel.nyandor_cat_recovered": "you recover the cat. it objects.",
  "pyxel.nyandor_depth_limit": "the assignment does not authorize deeper travel.",
  "pyxel.feel_warm_all_over": "you feel warm all over",
  "pyxel.feel_weaker": "you feel weaker!",
  "pyxel.gold_pieces": "{gold} gold pieces",
  "pyxel.have_found_trap": "you have found {trap}",
  "pyxel.hear_humming_noise": "you hear a humming noise",
  "pyxel.it_is_item": "It is a {item}",
  "pyxel.item_glows_blue": "your {item} glows blue!",
  "pyxel.item_vanishes_as_hits_ground": "The {item} vanishes as it hits the ground",
  "pyxel.its_cursed": "It's cursed!",
  "pyxel.language_english": "Language: English",
  "pyxel.language_japanese": "Language: Japanese",
  "pyxel.maniacal_laughter_echoes": "Maniacal laughter echoes",
  "pyxel.map_appears_in_mind": "A map appears in your mind!",
  "pyxel.monster_appears": "A monster appears!",
  "pyxel.monster_gaze_confused": "{monster}'s gaze has confused you",
  "pyxel.monster_hit_you": "the {monster} hit you",
  "pyxel.monster_is_defeated": "The {monster} is defeated!",
  "pyxel.monster_misses": "the {monster} misses",
  "pyxel.nearby_monsters_freeze": "Nearby monsters freeze!",
  "pyxel.nothing_here": "Nothing here",
  "pyxel.nothing_to_action": "Nothing to {action}",
  "pyxel.nothing_to_call": "nothing to call",
  "pyxel.nothing_to_eat": "nothing to eat",
  "pyxel.nothing_to_quaff": "nothing to quaff",
  "pyxel.nothing_to_wear": "nothing to wear",
  "pyxel.nothing_to_wield": "nothing to wield",
  "pyxel.nothing_to_zap": "nothing to zap",
  "pyxel.now_wearing_item": "you are now wearing {item}",
  "pyxel.pack_too_full": "pack too full",
  "pyxel.pack_turns_color": "your pack turns {color}!",
  "pyxel.palette_set": "Palette: {palette}",
  "pyxel.pick_up_item": "you pick up the {item}",
  "pyxel.pickup_off": "Pickup OFF",
  "pyxel.pickup_on": "Pickup ON",
  "pyxel.put_on_item": "you put on the {item}",
  "pyxel.remove_item": "you remove the {item}",
  "pyxel.rise_to_level": "you rise to level {level}!",
  "pyxel.scroll_is_blank": "This scroll is blank",
  "pyxel.see_item_here": "you see a {item} here",
  "pyxel.sense_magic": "you sense magic",
  "pyxel.sense_monsters": "you sense monsters",
  "pyxel.she_stole_item": "She stole your {item}!",
  "pyxel.somebody_watches_over_you": "Somebody watches over you",
  "pyxel.speed_up": "you speed up!",
  "pyxel.starve_to_death": "you starve to death",
  "pyxel.strength_plus_one": "Str +1!",
  "pyxel.swing_empty_air": "you swing at empty air",
  "pyxel.teleported": "you are teleported!",
  "pyxel.thrown_item_hits_monster_damage": "The {item} hits the {monster}. ({damage})",
  "pyxel.thrown_item_misses_monster": "The {item} misses the {monster}",
  "pyxel.unable_to_move": "you are unable to move",
  "pyxel.welcome_to_dungeons": "Hello {name}, welcome to the Dungeons of Doom!",
  "pyxel.welcome_to_level": "Welcome to level {level}!",
  "pyxel.wield_item": "you wield the {item}",
  "pyxel.wrenching_sensation_gut": "you feel a wrenching sensation in your gut",
  "settings.auto_pickup": "Auto pickup",
  "settings.diagonal_assist": "Diagonal assist",
  "settings.guide": "Up/Down: Select  A: Edit  Left/Right: Tabs  B: Close",
  "settings.language": "Language",
  "settings.off": "OFF",
  "settings.on": "ON",
  "settings.palette": "Palette",
  "ui.direction_prompt": "Which direction?",
  "ui.ctrl": "Ctl",
  "ui.ctrl_8way": "8w",
  "ui.ctrl_auto": "Auto",
  "ui.ctrl_diag": "Diag",
  "ui.ctrl_manual": "Man",
  "ui.effects": "Cond",
  "ui.equip": "Equip",
  "ui.food": "Food",
  "ui.food_faint": "Faint",
  "ui.food_hungry": "Hungry",
  "ui.food_normal": "Normal",
  "ui.food_weak": "Weak",
  "ui.name_entry": "Name Entry",
  "ui.name_entry_label": "Name",
  "ui.name_entry_move_hint": "D-pad/Arrows: Change/Move",
  "ui.name_entry_ok_hint": "A/Enter NEXT/END  Start/Space OK  B/Esc DEL",
  "ui.no_scores_yet": "No scores yet.",
  "ui.press_confirm_new_game": "A / Start  New game",
  "ui.press_confirm_scores": "A / Start  Scoreboard",
  "ui.done": "END",
  "ui.name_value": "Name: {name}",
  "ui.user_value": "User: {user}",
  "ui.status_normal": "NORMAL",
  "ui.loading": "Loading...",
  "ui.death_title": "R.I.P.",
  "ui.death_epitaph": "Here lies a brave rogue.",
  "ui.death_cause": "Cause: {cause}",
  "ui.score_header": "Top Ten Scores:",
  "ui.result_depth": "Depth: {depth}",
  "ui.result_exp": "Exp:   {exp}",
  "ui.result_gold": "Gold:  {gold}",
  "ui.result_level": "Level: {level}",
  "ui.result_turn": "Turn:  {turn}",
  "ui.quit_confirm_hint": "A/Start: quit  B/Esc: cancel",
  "ui.result_quit": "Quit",
  "ui.result_victory": "Victory",
  "ui.top_10": "Scoreboard",
  "ui.nyandor_victory_line_1": "You recovered the guild's cat",
  "ui.nyandor_victory_line_2": "and returned safely.",
  "ui.victory_line_1": "You escaped from the Dungeons of Doom",
  "ui.victory_line_2": "with the Amulet of Yendor.",
  "ui.trap_direction_prompt": "Which direction?",
  "ui.you_quit_with_gold": "You quit with {gold} gold pieces.",
  "pyxel.you_hit_monster": "you hit the {monster}",
  "pyxel.you_miss_monster": "you miss the {monster}",
  "rings.it_would_be_difficult_to_wrap_that_around_a_finger": "it would be difficult to wrap that around a finger",
  "rings.item_item2": "{item} ({item2})",
  "rings.l_or_r": "L or R",
  "rings.left_hand_or_right_hand": "left hand or right hand? ",
  "rings.left_or_right_ring": "left or right ring? ",
  "rings.no_rings": "no rings",
  "rings.not_a_ring": "not a ring",
  "rings.not_wearing_such_a_ring": "not wearing such a ring",
  "rings.please_type_l_or_r": "please type L or R",
  "rings.was_wearing_item_item2": "was wearing {item}({item2})",
  "rings.wearing_two": "wearing two",
  "rings.you_already_have_a_ring_on_each_hand": "you already have a ring on each hand",
  "rings.you_are_now_wearing": "you are now wearing ",
  "rings.you_arent_wearing_any_rings": "you aren't wearing any rings",
  "save.blank": "",
  "save.file_exists_do_you_wish_to_overwrite_it": "File exists.  Do you wish to overwrite it?",
  "save.file_name": "file name: ",
  "save.file_name_file": "file name: {file}",
  "save.please_answer_y_or_n": "please answer Y or N",
  "save.please_answer_y_or_n_2": "Please answer Y or N",
  "save.save_file_file": "save file ({file})? ",
  "scrolls.freeze": " freeze",
  "scrolls.nothing_to_read": "nothing to read",
  "scrolls.oh_now_this_scroll_has_a_map_on_it": "oh, now this scroll has a map on it",
  "scrolls.s": "s",
  "scrolls.s_around_you": "s around you",
  "scrolls.the_monster": "the monster",
  "scrolls.the_monster_freezes": "the monster freezes",
  "scrolls.the_monsters_around_you_freeze": "the monsters around you freeze",
  "scrolls.there_is_nothing_on_it_to_read": "there is nothing on it to read",
  "scrolls.this_scroll_is_an_item_scroll": "this scroll is an {item} scroll",
  "scrolls.what_a_puzzling_scroll": "what a puzzling scroll!",
  "scrolls.you_fall_asleep": "you fall asleep",
  "scrolls.you_feel_a_strange_sense_of_loss": "you feel a strange sense of loss",
  "scrolls.you_feel_as_if_somebody_is_watching_over_you": "you feel as if somebody is watching over you",
  "scrolls.you_feel_in_touch_with_the_universal_onenes": "you feel in touch with the Universal Onenes",
  "scrolls.you_hear_a_faint_cry_of_anguish_in_the_distance": "you hear a faint cry of anguish in the distance",
  "scrolls.you_hear_a_high_pitched_humming_noise": "you hear a high pitched humming noise",
  "scrolls.you_hear_maniacal_laughter_in_the_distance": "you hear maniacal laughter in the distance",
  "scrolls.your_armor_glows_color_for_a_moment": "your armor glows {color} for a moment",
  "scrolls.your_armor_is_covered_by_a_shimmering_color_shield": "your armor is covered by a shimmering {color} shield",
  "scrolls.your_color_glows_color2_for_a_moment": "your {color} glows {color2} for a moment",
  "scrolls.your_hands_begin_to_glow_color": "your hands begin to glow {color}",
  "scrolls.your_nose_tingles_and_you_smell_food": "your nose tingles and you smell food",
  "scrolls.your_nose_tingles": "your nose tingles",
  "sticks.by_a_shimmering_color_light": " by a shimmering {color} light",
  "sticks.missle_vanishes": "missle vanishes",
  "sticks.nothing_happens": "nothing happens",
  "sticks.off_the_dragon": " off the dragon",
  "sticks.the_corridor_glows_and_then_fades": "the corridor glows and then fades",
  "sticks.the_flame_bounces": "the flame bounces",
  "sticks.the_missle_vanishes_with_a_puff_of_smoke": "the missle vanishes with a puff of smoke",
  "sticks.the_room_is_lit": "the room is lit",
  "sticks.the_value_bounces": "the {value} bounces",
  "sticks.the_value_hits": "the {value} hits",
  "sticks.the_value_whizzes_by_you": "the {value} whizzes by you",
  "sticks.the_value_whizzes_past_value2": "the {value} whizzes past {value2}",
  "sticks.value_misses": "{value} misses",
  "sticks.what_a_bizarre_schtick": "what a bizarre schtick!",
  "sticks.you_are_hit_by_the_value": "you are hit by the {value}",
  "sticks.you_are_too_weak_to_use_it": "you are too weak to use it",
  "sticks.you_cant_zap_with_that": "you can't zap with that!",
  "sticks.you_have_a_tingling_feeling": "you have a tingling feeling",
  "things.bad_pick_one_count_from_count2_items": "bad pick_one: {count} from {count2} items",
  "things.blank": "",
  "things.blank_2": "? ",
  "things.dropped_item": "dropped {item}",
  "things.for": "for ",
  "things.for_all": "? (* for all)",
  "things.item_count": "{item}: {count}%",
  "things.not_a_type": "Not a type",
  "things.of_object_do_you_want_a_list": " of object do you want a list",
  "things.please_type_one_of_command_command2_command3_command4_escape_to_quit": "Please type one of {command}{command2}{command3}{command4} (ESCAPE to quit)",
  "things.there_is_something_there_already": "there is something there already",
  "things.what_type": "what type",
  "things.you_cant_it_appears_to_be_cursed": "you can't.  It appears to be cursed",
  "trap.arrow_trap": "arrow trap",
  "trap.bear_trap": "bear trap",
  "trap.dart_trap": "dart trap",
  "trap.mysterious_trap": "mysterious trap",
  "trap.rust_trap": "rust trap",
  "trap.sleeping_gas_trap": "sleeping gas trap",
  "trap.teleport_trap": "teleport trap",
  "trap.trap_door": "trap door",
  "weapons.the_item_vanishes_as_it_hits_the_ground": "the {item} vanishes as it hits the ground",
  "weapons.wielding_item_item2": "wielding {item} ({item2})",
  "weapons.you_are_now": "you are now ",
  "weapons.you_cant_wield_armor": "you can't wield armor",
  "wizard.blessing_n": "blessing? (+,-,n)",
  "wizard.how_much": "how much?",
  "wizard.type_of_item": "type of item: ",
  "wizard.which_command_do_you_want_0_f": "which {command} do you want? (0-f)",
  "wizard.wizard_s_password": "wizard's Password:",
  "wizard.you_dont_have_anything_in_your_pack_to_identify": "you don't have anything in your pack to identify",
  "wizard.you_must_identify_a_item": "you must identify a {item}",
  "wizard.you_must_identify_something": "you must identify something",
  "misc.what_to_call_it": "What do you want to call it? ",
  "misc.discoveries_title": "Discoveries",
  "misc.nothing_discovered": "(nothing discovered)",
  "misc.discoveries_hint": "[↑↓ scroll / A or Esc to close]"
}

JA_MESSAGES = {
  "armor.not_wearing_armor": "よろいは着ていない",
  "armor.was": "脱いだ:",
  "armor.wearing_item": "{item}を身につけた",
  "armor.wearing_item_item2": " {item}）{item2}を脱いだ",
  "armor.you_are_already_wearing_some": "他のよろいを着ている",
  "armor.you_are_now": "いま ",
  "armor.you_arent_wearing_any_armor": "よろいを着ていない",
  "armor.you_cant_wear_that": "それはよろいではない",
  "armor.you_ll_have_to_take_it_off_first": "。  まずそれを脱がなければならない",
  "armor.you_used_to_be": "さっきまで着ていたのは",
  "chase.couldnt_find_monster_in_runto_at_x_y": "runtoで怪物が見つからない ({x},{y})",
  "chase.in_some_bizarre_place_x_y": "奇妙な場所にいる ({x}, {y})",
  "command.a_secret_door": "隠しとびら",
  "command.blank": "",
  "command.call_it": "呼び名は？",
  "command.called_value": "「{value}」と呼ばれている",
  "command.character_you_want_help_for_for_all": "ヘルプを見る文字は？（*ですべて）: ",
  "command.food_left_count": "残り食糧: {count}",
  "command.i_see": "見えるのは",
  "command.i_see_no_way_down": "降りる階段がない",
  "command.i_see_no_way_up": "登る階段がない",
  "command.illegal_command_command": "コマンド「{command}」が違います",
  "command.inpack_count": "持ちもの数 = {count}",
  "command.item_value": "{item}）{value}",
  "command.no_monster_there": "その方向には怪物がいない",
  "command.no_trap_there": "その方向には、わながない",
  "command.not_wizard_any_more": "もうウィザードではない",
  "command.nothing_here": "ここには、何もない",
  "command.sorry": "残念",
  "command.that_has_already_been_identified": "それはもう正体がわかっている",
  "command.there_is": "ここには",
  "command.to_pick_up": "拾うものはない",
  "command.unknown_character_command": "「{command}」は知らない文字です",
  "command.value": " {value}",
  "command.value_nothing": "{value} 何もない",
  "command.value_value2": "{value}{value2}",
  "command.value_value2_2": "「{value}」: {value2}",
  "command.version_version_mctesq_was_here": "バージョン {version}. (mctesq was here)",
  "command.was": "以前は",
  "command.what_do_you_want_identified": "何を調べますか？ ",
  "command.what_do_you_want_to_call_it": "呼び名は？ ",
  "command.x_y": "@ {x},{y}",
  "command.you_are": "あなたは",
  "command.you_are_suddenly_as_smart_as_ken_arnold_in_dungeon_level": "急に地下{level}階のKen Arnoldと同じくらい賢くなった",
  "command.you_are_value": "{value}中（",
  "command.you_can_move_again": "ようやく体が自由になった",
  "command.you_cant_call_that_anything": "それには呼び名をつけることができない",
  "command.you_cant_you_re_floating_off_the_ground": "降りられない！",
  "command.you_feel_a_wrenching_sensation_in_your_gut": "胃袋をねじ切られるような気分がした。",
  "command.you_found": "見つけた: ",
  "command.you_have_found": "見つけたものは: ",
  "command.you_havent_typed_a_command_yet": "まだコマンドを入力していない",
  "command.your_way_is_magically_blocked": "階段は何者かの手によってふさがれている",
  "daemons.bummer_you_ve_hit_the_ground": "どすん！ 地面にぶつかった",
  "daemons.everything_looks_so_boring_now": "やっと、あたりの景色が元どおりになった",
  "daemons.far_out_everything_is_all_cosmic_again": "ふにゃ？ また何もかもが虹色に見えるなあ",
  "daemons.getting_hungry": "空腹になってきた",
  "daemons.getting_the_munchies": "腹が減ってきた",
  "daemons.the_munchies_are_interfering_with_your_motor_capabilites": "空腹で、体がうまく動かない",
  "daemons.the_munchies_overpower_your_motor_capabilities": "空腹で、体が動かなくなってきた。  ",
  "daemons.the_veil_of_darkness_lifts": "暗闇のとばりが上がってゆく",
  "daemons.you_are_getting_the_munchies": "腹が減ってきた",
  "daemons.you_are_starting_to_feel_weak": "空腹のせいで力がなくなってきた",
  "daemons.you_are_starting_to_get_hungry": "空腹になってきた",
  "daemons.you_faint": "空腹で、目がくらくらする",
  "daemons.you_feel_less_value_now": "少し{value}ではなくなった",
  "daemons.you_feel_too_weak_from_lack_of_food": "空腹のせいで力が出ない。  ",
  "daemons.you_feel_yourself_slowing_down": "素早くなる薬の効き目がなくなった",
  "daemons.you_float_gently_to_the_ground": "ようやく地面に足がついた",
  "daemons.you_freak_out": "目がくらくらする",
  "extern.a_beartrap": "熊のわな",
  "extern.a_mysterious_trap": "不思議なわな",
  "extern.a_poison_dart_trap": "毒矢のわな",
  "extern.a_rust_trap": "水のわな",
  "extern.a_sleeping_gas_trap": "催眠ガスのわな",
  "extern.a_teleport_trap": "テレポートのわな",
  "extern.a_trapdoor": "落し穴のわな",
  "extern.an_arrow_trap": "矢のわな",
  "fight.a_bite_has_weakened_you": "噛まれて、毒にやられた！",
  "fight.a_bite_momentarily_weakens_you": "一瞬、噛まれて力が抜けた",
  "fight.barely_miss": "はかろうじてそれた",
  "fight.barely_misses": "はかろうじてそれた",
  "fight.bite_has_no_effect": "噛まれたが、何も起こらなかった",
  "fight.blank": "。  ",
  "fight.by_the_subject": "{subject}につかまって",
  "fight.defeated": "。  倒した ",
  "fight.defeated_2": "倒した ",
  "fight.defeated_target": "{target}を倒した",
  "fight.doesnt_hit": "は命中しなかった",
  "fight.dont_hit": "は命中しなかった",
  "fight.has_injured": "は傷を負わせた ",
  "fight.have_injured": "は傷を負わせた ",
  "fight.heavy_that_s_a_nasty_critter": "重い！ なんていやな怪物だ！",
  "fight.hit": "は命中した。 ",
  "fight.miss": "はそれた",
  "fight.misses": "はそれた。 ",
  "fight.monster_hit": "{subject}の攻撃は命中した",
  "fight.monster_hit_excellent": "{subject}の攻撃は見事に命中した",
  "fight.monster_hit_injured": "{subject}の攻撃で傷を負った",
  "fight.monster_hit_swing": "{subject}は振って命中させた",
  "fight.monster_miss": "{subject}の攻撃はそれた",
  "fight.monster_miss_barely": "{subject}の攻撃はかろうじてそれた",
  "fight.monster_miss_doesnt_hit": "{subject}の攻撃は命中しなかった",
  "fight.monster_miss_swing": "{subject}は振ったがそれた",
  "fight.player_hit": "{target}への攻撃は命中した",
  "fight.player_hit_excellent": "{target}に見事な一撃を与えた",
  "fight.player_hit_injured": "{target}に傷を負わせた",
  "fight.player_hit_swing": "{target}へ振って命中させた",
  "fight.player_miss": "{target}への攻撃はそれた",
  "fight.player_miss_barely": "{target}への攻撃はかろうじてそれた",
  "fight.player_miss_dont_hit": "{target}への攻撃は命中しなかった",
  "fight.player_miss_swing": "{target}へ振ったがそれた",
  "fight.scored_an_excellent_hit_on": "は見事に命中した ",
  "fight.she_stole_target": "{target}を盗まれた！",
  "fight.subject": "{subject}",
  "fight.subject_2": " {subject}",
  "fight.subject_appears_confused": "{subject}は混乱したようだ",
  "fight.swing_and_hit": "は振って命中した ",
  "fight.swing_and_miss": "は振ったがそれた",
  "fight.swings_and_hits": "は振って命中した ",
  "fight.swings_and_misses": "は振ったがそれた",
  "fight.the_subject_hits": "{subject}の攻撃は命中した。 ",
  "fight.the_subject_misses": "{subject}の攻撃はそれた。 ",
  "fight.thrown_weapon_hits": "{item}が{target}に命中した",
  "fight.thrown_weapon_misses": "{item}は{target}に命中しなかった",
  "fight.wait_that_s_a_xeroc": "おっと、こいつは物まねの怪物だ！",
  "fight.you_are_frozen": "{subject}に凍りつかされ、動けない！",
  "fight.you_feel_a_bite_in_your_leg_and_now_feel_weaker": "足を噛まれ、力が抜けていく",
  "fight.you_have": "あなたは",
  "fight.you_have_defeated_target": "{target}を倒した",
  "fight.you_hit": "あなたの攻撃は命中した ",
  "fight.you_hit_target": "{target}に命中した",
  "fight.you_missed": "あなたの攻撃はそれた ",
  "fight.you_missed_target": "{target}に当たらなかった",
  "fight.you_suddenly_feel_weaker": "強さが減ってしまった！",
  "fight.your_hands_stop_glowing_color": "手の{color}い輝きが消えた",
  "fight.your_purse_feels_lighter": "金塊を盗まれた！",
  "io.blank": "",
  "io.faint": "空腹で、もう死にそうだ。",
  "io.hungry": "空腹になってきた。",
  "io.level_level_gold_gold_hp_hp_width_hp_str_max_hp_width_max_hp_arm_strengt": "階: {level}  金塊: {gold}  体力: {hp_width}({hp})  強さ: {max_hp_width}({max_hp})  守備: {strength}  経験: {max_strength}/{armor}  {exp_level}",
  "io.weak": "空腹のせいで力がなくなってきた。",
  "info.guide_default": "左右: タブ   Select/B: 閉じる",
  "info.guide_log": "上下: スクロール   左右: タブ   Select/B: 閉じる",
  "info.help": "ヘルプ",
  "info.inventory": "持ちもの",
  "info.log": "ログ",
  "info.settings": "設定",
  "info.title": "情報",
  "item.being_worn": "（着ている）",
  "item.on_left_hand": "（左手）",
  "item.on_right_hand": "（右手）",
  "item.protection": "防護 {value}",
  "item.weapon_in_hand": "（使っている）",
  "list.ran_out_of_memory_after_count_items": "{count}個の項目でメモリーが足りなくなった。",
  "main.really_quit": "本当にやめますか？",
  "menu.action": "行動",
  "menu.assist": "補助",
  "menu.call": "名付け",
  "menu.discoveries": "発見",
  "menu.drop": "落とす",
  "menu.eat": "食べる",
  "menu.help": "ヘルプ",
  "menu.identify": "識別",
  "menu.inventory": "持ちもの",
  "menu.language": "言語",
  "menu.palette": "パレット",
  "menu.pickup": "自動拾い",
  "menu.picky_inventory": "持ちもの",
  "menu.quit": "終了",
  "menu.put_on": "指輪をはめる",
  "menu.quaff": "飲む",
  "menu.read": "読む",
  "menu.remove_ring": "指輪をはずす",
  "menu.search": "探す",
  "menu.take_off": "はずす",
  "menu.take_off_armor": "よろいを脱ぐ",
  "menu.throw": "投げる",
  "menu.trap": "罠",
  "menu.wear": "よろいを着る",
  "menu.wield": "武器にする",
  "menu.zap": "振る",
  "misc.call_it": "呼び名は？",
  "misc.in_use": "その武器はもう使っている",
  "misc.my_that_was_a_yummy_value": "おや、なんて甘い{value}だ",
  "misc.that_s_already": "それはもう",
  "misc.that_s_inedible": "それは食べられない",
  "misc.ugh_you_would_get_ill_if_you_ate_that": "うっ、それを食べると気分が悪くなりそうだ",
  "misc.value_that_tasted_good": "{value}、おいしかった",
  "misc.value_this_food_tastes_awful": "{value}、まずい！",
  "misc.welcome_to_level_level": "レベル{level}へようこそ",
  "misc.what_do_you_want_to_call_it": "呼び名は？ ",
  "misc.which_direction": "方角は？ ",
  "misc.yuk": "げげっ",
  "misc.yum": "うん",
  "misc.you_faint_from_exhaustion": "疲れきって気を失った",
  "monsters.blank": "の",
  "monsters.cant_find_monster_in_wake_monster": "wake_monsterで怪物が見つからない。",
  "monsters.s_gaze_has_confused_you": "ににらまれ、頭が混乱してしまった！",
  "monsters.started_a_wandering_subject": "歩き回る{subject}を出した。",
  "monsters.subject": "{subject}",
  "move.a_color_light_flashes_in_your_eyes": "{color}光が目の前でひらめいた",
  "move.a_gush_of_water_hits_you_on_the_head": "頭の上から大量の水が降ってきた！",
  "move.a_poisoned_dart_killed_you": "毒矢にやられて死んだ",
  "move.a_small_dart_just_hit_you_in_the_shoulder": "小さな投げ矢が飛んできて、肩にささった！",
  "move.a_small_dart_whizzes_by_your_ear_and_vanishes": "小さな投げ矢が耳元をかすめ、消え去った",
  "move.a_spike_shoots_past_your_ear": "とげが耳元をかすめて飛んでいった！",
  "move.a_strange_white_mist_envelops_you_and_you_fall_asleep": "不思議なもやにつつまれ、眠り込んでしまった！",
  "move.an_arrow_killed_you": "矢に射抜かれて死んだ",
  "move.an_arrow_shoots_past_you": "矢があなたのそばを飛び去った",
  "move.multi_colored_lines_swirl_around_you_then_fade": "色とりどりの線がまわりを渦巻き、やがて消えた",
  "move.oh_no_an_arrow_shot_you": "しまった！ 矢に射られた",
  "move.the_light_in_here_suddenly_seems_color": "あたりの光が急に{color}に見えてきた",
  "move.the_rust_vanishes_instantly": "水ごけの湿り気はすぐに消え去った",
  "move.time_now_seems_to_be_going_slower": "時間の流れが遅くなったようだ",
  "move.value_sparks_dance_across_your_armor": "{value}の火花がよろいの上で踊った",
  "move.you_are_being_held": "怪物につかまえられて、逃げられない",
  "move.you_are_caught_in_a_bear_trap": "熊のわなにつかまった！",
  "move.you_are_still_stuck_in_the_bear_trap": "熊のわなが、なかなかはずれない",
  "move.you_are_suddenly_in_a_parallel_dimension": "急に別の次元に入りこんだ",
  "move.you_feel_a_sting_in_the_side_of_your_neck": "首すじにちくりとした痛みを感じた",
  "move.you_feel_time_speed_up_suddenly": "急に時間の流れが速くなったようだ",
  "move.you_fell_into_a_trap": "急に床がくずれ、足元から落ちてしまった！",
  "move.you_pack_turns_value": "持ちものが{value}になった！",
  "move.you_suddenly_feel_very_thirsty": "急にとても喉が渇いた",
  "move.your_armor_appears_to_be_weaker_now_oh_my": "よろいが弱くなったようだ。 おやまあ！",
  "move.your_armor_weakens": "よろいはさびてしまった！",
  "pack.a_item": "a）{item}",
  "pack.blank": "",
  "pack.count_gold_pieces": "{count}個の金塊",
  "pack.empty_handed": "持ちものなし",
  "pack.for_list": "? (*で一覧): ",
  "pack.in_your_pack": "",
  "pack.item": "持ちもの: ",
  "pack.item_is_not_a_valid_item": "「{item}」は持ちものではない",
  "pack.item_item2": "{item}（{item2}）",
  "pack.item_item2_2": "{item}）{item2}",
  "pack.item_not_in_pack": "「{item}」は持っていない",
  "pack.moved_onto_item": "{item}の上にいる",
  "pack.no_room": "もうこれ以上、物は持てない",
  "pack.nothing_appropriate": "それは１つも持っていない",
  "pack.the_scroll_turns_to_dust_as_you_pick_it_up": "拾いあげたとたん、巻き物はちりになってしまった",
  "pack.there_s": "",
  "pack.what": "どれ",
  "pack.which_item_do_you_wish_to_inventory": "調べる持ちものは？ ",
  "pack.which_object_do_you_want_to": "どの持ちものを",
  "pack.you": "プレイヤー",
  "pack.you_are_empty_handed": "持ちものは、１つも持っていない",
  "pack.you_arent_carrying_anything": "持ちものは、１つも持っていない",
  "pack.you_dont_have_anything_appropriate": "それは１つも持っていない",
  "pack.you_found": "見つけた: ",
  "pack.you_now_have": "手に入れた: ",
  "pack.you_ran_out": "もう残っていない",
  "passages.warning_connectivity_problem_on_this_level": "この階の通路接続に問題がある。",
  "potions.a_cloak_of_darkness_falls_around_you": "深い暗闇のとばりがあたりをおおってゆく",
  "potions.hey_this_tastes_great_it_make_you_feel_warm_all_over": "これはうまい！ からだがポカポカしてきた",
  "potions.oh_bummer_everything_is_dark_help": "しまった！ 何も見えない！ 助けて！",
  "potions.oh_wow_everything_seems_so_cosmic": "ふにゃ？ 何もかもが虹色にみえるなあ？",
  "potions.oh_wow_you_re_floating_in_the_air": "降りられない！",
  "potions.that_s_undrinkable": "それは水薬ではない",
  "potions.wait_what_s_going_on_here_huh_what_who": "あれ？ ここはどこ？ 私はだれ？",
  "potions.what_a_tripy_feeling": "何だか酔っぱらいみたいな気分だ！",
  "potions.what_an_odd_tasting_potion": "なんとも妙な味の水薬だ！",
  "potions.you_begin_to_feel_better": "気分がよくなった！",
  "potions.you_begin_to_feel_much_better": "とても気分がよくなった！",
  "potions.you_feel_momentarily_sick": "一瞬気分が悪くなった",
  "potions.you_feel_stronger_now_what_bulging_muscles": "何だか、力がわいてくるぞ！",
  "potions.you_feel_very_sick_now": "この水薬は毒だった！",
  "potions.you_feel_yourself_moving_much_faster": "体が素早く動くようになった！",
  "potions.you_have_a_item_feeling_for_a_moment_then_it_passes": "{item}な気分に一瞬おそわれたが、すぐに消えた",
  "potions.you_start_to_float_in_the_air": "体が宙に浮いてしまった！",
  "potions.you_suddenly_feel_much_more_skillful": "急に腕前が上がったような気がした",
  "potions.this_potion_tastes_like_item_juice": "この水薬は{item}ジュースのような味がする",
  "potions.yuk_why_would_you_want_to_drink_that": "げげっ！ どうしてそんなものを飲みたいんだ？",
  "pyxel.already_ring_each_hand": "両手に指輪をしている",
  "pyxel.are_weak": "空腹のせいで力がなくなってきた",
  "pyxel.armor_glows": "よろいが輝いた！",
  "pyxel.can_see_invisible_monsters": "見えない怪物が見える",
  "pyxel.cant_appears_cursed": "はずせない。のろわれているようだ",
  "pyxel.cant_let_go": "手放せない！",
  "pyxel.cant_let_go_short": "手放せない！",
  "pyxel.color_sparks_dance_armor": "{color}の火花がよろいの上で踊った",
  "pyxel.cursed_armor_wont_come_off": "のろわれたよろいは脱げない！",
  "pyxel.darkness_falls": "暗闇に包まれた",
  "pyxel.defeated_monster_exp": "{monster}を倒した。 (経験: {exp})",
  "pyxel.descend_to_depth": "地下{depth}階へ降りた...",
  "pyxel.diagonal_assist_off": "斜め補助モード オフ",
  "pyxel.diagonal_assist_on": "斜め補助モード オン",
  "pyxel.died_restart": "あなたは死んだ... [A/Start] で再開",
  "pyxel.drop_item": "{item}を落とした",
  "pyxel.dungeon_depth": "地下{depth}階",
  "pyxel.eat_item_yum": "{item}を食べた。うまい！",
  "pyxel.equipment_feels_lighter": "装備が軽くなった",
  "pyxel.escaped_with_amulet": "イェンダーの魔除けを持って脱出した！",
  "pyxel.escaped_with_nyandor": "ギルドの大切なねこを連れ戻した。",
  "pyxel.faint_from_lack_of_food": "空腹で、目がくらくらする",
  "pyxel.fall_asleep": "知らないうちに眠り込んでしまった。",
  "pyxel.feel_better_amount": "体力が回復した。 (+{count})",
  "pyxel.feel_confused": "混乱してきた",
  "pyxel.feel_confused_bang": "混乱してきた！",
  "pyxel.feel_hungry": "空腹になってきた",
  "pyxel.feel_much_better_amount": "体力が大きく回復した。 (+{count})",
  "pyxel.feel_sense_of_loss": "何かを失ったような気がした",
  "pyxel.feel_sick_strength_loss": "気分が悪くなった。 (強さ -{count})",
  "pyxel.feel_vaguely_uneasy": "なんとなく不安な気分になった",
  "pixel.nyandor_cat_recovered": "ねこを回収した。ねこは不満そうだ。",
  "pixel.nyandor_vitory_line1": "ギルドの大切なねこを回収した",
  "pixel.nyandor_vitory_line2": "そして地上へ連れ戻した。",
  "pyxel.nyandor_cat_drop_blocked": "このねこを置いていくわけにはいかない。",
  "pyxel.nyandor_cat_recovered": "ねこを回収した。ねこは不満そうだ。",
  "pyxel.nyandor_depth_limit": "任務はこれ以上の降下を許可していない。",
  "pyxel.feel_warm_all_over": "体が温かくなった",
  "pyxel.feel_weaker": "強さが減ってしまった！",
  "pyxel.gold_pieces": "{gold}個の金塊",
  "pyxel.have_found_trap": "{trap}を見つけている",
  "pyxel.hear_humming_noise": "低いうなり声が聞こえる",
  "pyxel.it_is_item": "それは{item}だ",
  "pyxel.item_glows_blue": "{item}が青く輝いた！",
  "pyxel.item_vanishes_as_hits_ground": "{item}は地面に落ちると消えた",
  "pyxel.its_cursed": "のろわれている！",
  "pyxel.language_english": "言語: 英語",
  "pyxel.language_japanese": "言語: 日本語",
  "pyxel.maniacal_laughter_echoes": "狂った笑い声が響いた",
  "pyxel.map_appears_in_mind": "頭の中に地図が浮かんだ！",
  "pyxel.monster_appears": "怪物が現れた！",
  "pyxel.monster_gaze_confused": "{monster}の凝視で混乱した",
  "pyxel.monster_hit_you": "{monster}の攻撃は命中した",
  "pyxel.monster_is_defeated": "{monster}を倒した！",
  "pyxel.monster_misses": "{monster}の攻撃はそれた",
  "pyxel.nearby_monsters_freeze": "近くの怪物が動きを止めた！",
  "pyxel.nothing_here": "ここには、何もない",
  "pyxel.nothing_to_action": "{action}ものがない",
  "pyxel.nothing_to_call": "名付けるものがない",
  "pyxel.nothing_to_eat": "食べるものがない",
  "pyxel.nothing_to_quaff": "飲むものがない",
  "pyxel.nothing_to_wear": "着るものがない",
  "pyxel.nothing_to_wield": "武器がない",
  "pyxel.nothing_to_zap": "振るものがない",
  "pyxel.now_wearing_item": "{item}を身につけた",
  "pyxel.pack_too_full": "もうこれ以上、物は持てない",
  "pyxel.pack_turns_color": "荷物が{color}に変わった！",
  "pyxel.palette_set": "パレット: {palette}",
  "pyxel.pick_up_item": "{item}を手に入れた",
  "pyxel.pickup_off": "自動拾い オフ",
  "pyxel.pickup_on": "自動拾い オン",
  "pyxel.put_on_item": "{item}を身につけた",
  "pyxel.remove_item": "{item}をはずした",
  "pyxel.rise_to_level": "レベル{level}に上がった！",
  "pyxel.scroll_is_blank": "この巻き物は白紙だ",
  "pyxel.see_item_here": "{item}の上にいる",
  "pyxel.sense_magic": "魔法の気配を感じた",
  "pyxel.sense_monsters": "怪物の気配を感じた",
  "pyxel.she_stole_item": "{item}を盗まれた！",
  "pyxel.somebody_watches_over_you": "誰かに見守られている気がする",
  "pyxel.speed_up": "素早くなった！",
  "pyxel.starve_to_death": "空腹で、もう死にそうだ",
  "pyxel.strength_plus_one": "強さが増した！",
  "pyxel.swing_empty_air": "空を切った",
  "pyxel.teleported": "テレポートした！",
  "pyxel.thrown_item_hits_monster_damage": "{item}が{monster}に当たった。 ({damage})",
  "pyxel.thrown_item_misses_monster": "{item}は{monster}に当たらなかった",
  "pyxel.unable_to_move": "動けない",
  "pyxel.welcome_to_dungeons": "やあ {name}、運命の洞窟へようこそ",
  "pyxel.welcome_to_level": "レベル{level}へようこそ",
  "pyxel.wield_item": "{item}を武器にした",
  "pyxel.wrenching_sensation_gut": "胃袋をねじ切られるような気分がした。",
  "settings.auto_pickup": "自動拾い",
  "settings.diagonal_assist": "斜め補助",
  "settings.guide": "上下: 選択  A: 変更  左右: タブ  B: 閉じる",
  "settings.language": "言語",
  "settings.off": "OFF",
  "settings.on": "ON",
  "settings.palette": "パレット",
  "ui.direction_prompt": "どの方向?",
  "ui.ctrl": "操作",
  "ui.ctrl_8way": "8方",
  "ui.ctrl_auto": "自動",
  "ui.ctrl_diag": "斜め",
  "ui.ctrl_manual": "手動",
  "ui.effects": "状態",
  "ui.equip": "装備",
  "ui.food": "食料",
  "ui.food_faint": "衰弱",
  "ui.food_hungry": "空腹",
  "ui.food_normal": "通常",
  "ui.food_weak": "弱い",
  "ui.name_entry": "名前入力",
  "ui.name_entry_label": "名前",
  "ui.name_entry_move_hint": "D-pad/矢印: 変更/移動",
  "ui.name_entry_ok_hint": "A/Enter 次/終了  Start/Space 決定  B/Esc 削除",
  "ui.no_scores_yet": "まだ記録がない。",
  "ui.press_confirm_new_game": "A / Start  新しいゲーム",
  "ui.press_confirm_scores": "A / Start  スコアボード",
  "ui.done": "完了",
  "ui.name_value": "名前: {name}",
  "ui.user_value": "ユーザ: {user}",
  "ui.status_normal": "通常",
  "ui.loading": "ロード中...",
  "ui.death_title": "安らかに眠れ",
  "ui.death_epitaph": "ここに勇敢なローグ眠る",
  "ui.death_cause": "死因: {cause}",
  "ui.score_header": "順位   得点    名前",
  "ui.result_depth": "地下{depth}階",
  "ui.result_exp": "経験: {exp}",
  "ui.result_gold": "{gold}個の金塊",
  "ui.result_level": "レベル: {level}",
  "ui.result_turn": "ターン: {turn}",
  "ui.quit_confirm_hint": "A/Start: 終了  B/Esc: 戻る",
  "ui.result_quit": "終了",
  "ui.result_victory": "勝利",
  "ui.top_10": "スコアボード",
  "ui.nyandor_victory_line_1": "ギルドの大切なねこを回収した",
  "ui.nyandor_victory_line_2": "そして地上へ連れ戻した。",
  "ui.victory_line_1": "ダンジョンから脱出した",
  "ui.victory_line_2": "イェンダーの魔除けとともに。",
  "ui.trap_direction_prompt": "どの方向?",
  "ui.you_quit_with_gold": "{gold}個の金塊を持って終了した。",
  "pyxel.you_hit_monster": "{monster}への攻撃は命中した",
  "pyxel.you_miss_monster": "{monster}への攻撃はそれた",
  "rings.it_would_be_difficult_to_wrap_that_around_a_finger": "それを指に巻くのはむずかしそうだ",
  "rings.item_item2": "{item}（{item2}）",
  "rings.l_or_r": "LかR",
  "rings.left_hand_or_right_hand": "左手(L)、それとも右手(R)？ ",
  "rings.left_or_right_ring": "左か右の指輪？ ",
  "rings.no_rings": "指輪はない",
  "rings.not_a_ring": "それは指輪ではない",
  "rings.not_wearing_such_a_ring": "そちらの手には指輪をしていない",
  "rings.please_type_l_or_r": "LかRを入力してください",
  "rings.was_wearing_item_item2": "{item}（{item2}）をはずした",
  "rings.wearing_two": "両手に指輪をしている",
  "rings.you_already_have_a_ring_on_each_hand": "すでに両手に指輪をしている",
  "rings.you_are_now_wearing": "いま身につけた: ",
  "rings.you_arent_wearing_any_rings": "指輪ははめていない",
  "save.blank": "",
  "save.file_exists_do_you_wish_to_overwrite_it": "ファイルがあります。 上書きしますか？",
  "save.file_name": "ファイル名: ",
  "save.file_name_file": "ファイル名: {file}",
  "save.please_answer_y_or_n": "YかNで答えてください。",
  "save.please_answer_y_or_n_2": "YかNで答えてください。",
  "save.save_file_file": "セーブファイル（{file}）？ ",
  "scrolls.freeze": "は動けなくなった",
  "scrolls.nothing_to_read": "読むものがない",
  "scrolls.oh_now_this_scroll_has_a_map_on_it": "おや、この巻き物には地図が書いてある！",
  "scrolls.s": "",
  "scrolls.s_around_you": "たち",
  "scrolls.the_monster": "怪物",
  "scrolls.the_monster_freezes": "怪物は動けなくなった！",
  "scrolls.the_monsters_around_you_freeze": "怪物どもは動けなくなった！",
  "scrolls.there_is_nothing_on_it_to_read": "それには読むところがない",
  "scrolls.this_scroll_is_an_item_scroll": "これは{item}を調べる巻き物だった",
  "scrolls.what_a_puzzling_scroll": "なんとも不可解な巻き物だ！",
  "scrolls.you_fall_asleep": "知らないうちに眠り込んでしまった",
  "scrolls.you_feel_a_strange_sense_of_loss": "急に、体から力が抜けていくような気がした",
  "scrolls.you_feel_as_if_somebody_is_watching_over_you": "ふっと、誰かに見つめられているような気がした",
  "scrolls.you_feel_in_touch_with_the_universal_onenes": "ふっと、女神の手に包まれているような気がした",
  "scrolls.you_hear_a_faint_cry_of_anguish_in_the_distance": "遠くから、かすかな怒りの叫びが聞こえる",
  "scrolls.you_hear_a_high_pitched_humming_noise": "どこからか、かん高いうなり声が聞こえてくる",
  "scrolls.you_hear_maniacal_laughter_in_the_distance": "遠くから、狂ったような笑い声が聞こえてくる",
  "scrolls.your_armor_glows_color_for_a_moment": "着ているよろいが、ほんの少し{color}の輝きに包まれた",
  "scrolls.your_armor_is_covered_by_a_shimmering_color_shield": "着ているよろいは、輝く{color}の光に守られた",
  "scrolls.your_color_glows_color2_for_a_moment": "手に持った{color}が、ほんの少し{color2}輝きに包まれた",
  "scrolls.your_hands_begin_to_glow_color": "手が{color}く輝きはじめた",
  "scrolls.your_nose_tingles_and_you_smell_food": "鼻がむずむずし、食料のにおいがした",
  "scrolls.your_nose_tingles": "何だか、鼻がむずむずする",
  "sticks.by_a_shimmering_color_light": "、輝く{color}の光に照らされた",
  "sticks.missle_vanishes": "魔法のミサイルは消えた",
  "sticks.nothing_happens": "しかし、何も起こらなかった",
  "sticks.off_the_dragon": "、ドラゴンにはね返された",
  "sticks.the_corridor_glows_and_then_fades": "通路が光り、やがて消えた",
  "sticks.the_flame_bounces": "ほのおは跳ね返った",
  "sticks.the_missle_vanishes_with_a_puff_of_smoke": "魔法のミサイルは煙とともに消えた",
  "sticks.the_room_is_lit": "部屋が明るくなった",
  "sticks.the_value_bounces": "{value}は跳ね返った",
  "sticks.the_value_hits": "{value}は命中した",
  "sticks.the_value_whizzes_by_you": "{value}があなたのそばを飛び去った",
  "sticks.the_value_whizzes_past_value2": "{value}が{value2}のそばを飛び去った",
  "sticks.value_misses": "{value}はそれた",
  "sticks.what_a_bizarre_schtick": "なんとも奇妙なつえだ！",
  "sticks.you_are_hit_by_the_value": "{value}に当たった",
  "sticks.you_are_too_weak_to_use_it": "弱りすぎて使えない",
  "sticks.you_cant_zap_with_that": "それを振りかざすことはできない",
  "sticks.you_have_a_tingling_feeling": "何だか、体がむずむずする",
  "things.bad_pick_one_count_from_count2_items": "bad pick_one: {count} / {count2} 個",
  "things.blank": "",
  "things.blank_2": "? ",
  "things.dropped_item": "{item}を落とした",
  "things.for": "どの",
  "things.for_all": "? (*ですべて)",
  "things.item_count": "{item}: {count}%",
  "things.not_a_type": "その種類はありません",
  "things.of_object_do_you_want_a_list": "の一覧を見ますか",
  "things.please_type_one_of_command_command2_command3_command4_escape_to_quit": "次のどれかを入力してください: {command}{command2}{command3}{command4}（ESCAPEで中止）",
  "things.there_is_something_there_already": "そこには、すでに何かが置かれている",
  "things.what_type": "どの種類のものですか？",
  "things.you_cant_it_appears_to_be_cursed": "呪われているので、それはできない！",
  "trap.arrow_trap": "矢の罠",
  "trap.bear_trap": "くくり罠",
  "trap.dart_trap": "毒矢の罠",
  "trap.mysterious_trap": "不思議な罠",
  "trap.rust_trap": "さびの罠",
  "trap.sleeping_gas_trap": "眠りガスの罠",
  "trap.teleport_trap": "テレポートの罠",
  "trap.trap_door": "落とし穴",
  "weapons.the_item_vanishes_as_it_hits_the_ground": "{item}は地面に落ちると、どこかに消えてしまった",
  "weapons.wielding_item_item2": "{item}（{item2}）に持ちかえた",
  "weapons.you_are_now": "いま ",
  "weapons.you_cant_wield_armor": "よろいを武器にすることはできない",
  "wizard.blessing_n": "祝福？ (+,-,n)",
  "wizard.how_much": "どれだけ？",
  "wizard.type_of_item": "持ちものの種類: ",
  "wizard.which_command_do_you_want_0_f": "どの{command}にしますか？ (0-f)",
  "wizard.wizard_s_password": "ウィザードのパスワード:",
  "wizard.you_dont_have_anything_in_your_pack_to_identify": "調べる持ちものは、１つも持っていない",
  "wizard.you_must_identify_a_item": "{item}を調べなければならない",
  "wizard.you_must_identify_something": "何かを調べなければならない",
  "misc.what_to_call_it": "名前をつける：",
  "misc.discoveries_title": "発見リスト",
  "misc.nothing_discovered": "（未発見）",
  "misc.discoveries_hint": "[↑↓スクロール / A または Esc で閉じる]"
}
